 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/attendancerecords", type: :request do
  
  # Attendancerecord. As you add validations to Attendancerecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Attendancerecord.create! valid_attributes
      get attendancerecords_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      attendancerecord = Attendancerecord.create! valid_attributes
      get attendancerecord_url(attendancerecord)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_attendancerecord_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      attendancerecord = Attendancerecord.create! valid_attributes
      get edit_attendancerecord_url(attendancerecord)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Attendancerecord" do
        expect {
          post attendancerecords_url, params: { attendancerecord: valid_attributes }
        }.to change(Attendancerecord, :count).by(1)
      end

      it "redirects to the created attendancerecord" do
        post attendancerecords_url, params: { attendancerecord: valid_attributes }
        expect(response).to redirect_to(attendancerecord_url(Attendancerecord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Attendancerecord" do
        expect {
          post attendancerecords_url, params: { attendancerecord: invalid_attributes }
        }.to change(Attendancerecord, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post attendancerecords_url, params: { attendancerecord: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested attendancerecord" do
        attendancerecord = Attendancerecord.create! valid_attributes
        patch attendancerecord_url(attendancerecord), params: { attendancerecord: new_attributes }
        attendancerecord.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the attendancerecord" do
        attendancerecord = Attendancerecord.create! valid_attributes
        patch attendancerecord_url(attendancerecord), params: { attendancerecord: new_attributes }
        attendancerecord.reload
        expect(response).to redirect_to(attendancerecord_url(attendancerecord))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        attendancerecord = Attendancerecord.create! valid_attributes
        patch attendancerecord_url(attendancerecord), params: { attendancerecord: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested attendancerecord" do
      attendancerecord = Attendancerecord.create! valid_attributes
      expect {
        delete attendancerecord_url(attendancerecord)
      }.to change(Attendancerecord, :count).by(-1)
    end

    it "redirects to the attendancerecords list" do
      attendancerecord = Attendancerecord.create! valid_attributes
      delete attendancerecord_url(attendancerecord)
      expect(response).to redirect_to(attendancerecords_url)
    end
  end
end
