 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/encounters", type: :request do
  
  # Encounter. As you add validations to Encounter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Encounter.create! valid_attributes
      get encounters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      encounter = Encounter.create! valid_attributes
      get encounter_url(encounter)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_encounter_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      encounter = Encounter.create! valid_attributes
      get edit_encounter_url(encounter)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Encounter" do
        expect {
          post encounters_url, params: { encounter: valid_attributes }
        }.to change(Encounter, :count).by(1)
      end

      it "redirects to the created encounter" do
        post encounters_url, params: { encounter: valid_attributes }
        expect(response).to redirect_to(encounter_url(Encounter.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Encounter" do
        expect {
          post encounters_url, params: { encounter: invalid_attributes }
        }.to change(Encounter, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post encounters_url, params: { encounter: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested encounter" do
        encounter = Encounter.create! valid_attributes
        patch encounter_url(encounter), params: { encounter: new_attributes }
        encounter.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the encounter" do
        encounter = Encounter.create! valid_attributes
        patch encounter_url(encounter), params: { encounter: new_attributes }
        encounter.reload
        expect(response).to redirect_to(encounter_url(encounter))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        encounter = Encounter.create! valid_attributes
        patch encounter_url(encounter), params: { encounter: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested encounter" do
      encounter = Encounter.create! valid_attributes
      expect {
        delete encounter_url(encounter)
      }.to change(Encounter, :count).by(-1)
    end

    it "redirects to the encounters list" do
      encounter = Encounter.create! valid_attributes
      delete encounter_url(encounter)
      expect(response).to redirect_to(encounters_url)
    end
  end
end
