 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/merchandises", type: :request do
  
  # Merchandise. As you add validations to Merchandise, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Merchandise.create! valid_attributes
      get merchandises_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      merchandise = Merchandise.create! valid_attributes
      get merchandise_url(merchandise)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_merchandise_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      merchandise = Merchandise.create! valid_attributes
      get edit_merchandise_url(merchandise)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Merchandise" do
        expect {
          post merchandises_url, params: { merchandise: valid_attributes }
        }.to change(Merchandise, :count).by(1)
      end

      it "redirects to the created merchandise" do
        post merchandises_url, params: { merchandise: valid_attributes }
        expect(response).to redirect_to(merchandise_url(Merchandise.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Merchandise" do
        expect {
          post merchandises_url, params: { merchandise: invalid_attributes }
        }.to change(Merchandise, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post merchandises_url, params: { merchandise: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested merchandise" do
        merchandise = Merchandise.create! valid_attributes
        patch merchandise_url(merchandise), params: { merchandise: new_attributes }
        merchandise.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the merchandise" do
        merchandise = Merchandise.create! valid_attributes
        patch merchandise_url(merchandise), params: { merchandise: new_attributes }
        merchandise.reload
        expect(response).to redirect_to(merchandise_url(merchandise))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        merchandise = Merchandise.create! valid_attributes
        patch merchandise_url(merchandise), params: { merchandise: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested merchandise" do
      merchandise = Merchandise.create! valid_attributes
      expect {
        delete merchandise_url(merchandise)
      }.to change(Merchandise, :count).by(-1)
    end

    it "redirects to the merchandises list" do
      merchandise = Merchandise.create! valid_attributes
      delete merchandise_url(merchandise)
      expect(response).to redirect_to(merchandises_url)
    end
  end
end
